# coding: utf-8

"""
    Xenia Python Client Library

    Python Client Library to interact with the Xenia API.  # noqa: E501

    The version of the OpenAPI document: v1.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from xenia_python_client_library.configuration import Configuration


class OrganizationUpdate(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'subscription': 'str',
        'subscription_agreed': 'bool'
    }

    attribute_map = {
        'subscription': 'subscription',
        'subscription_agreed': 'subscription_agreed'
    }

    def __init__(self, subscription=None, subscription_agreed=None, local_vars_configuration=None):  # noqa: E501
        """OrganizationUpdate - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._subscription = None
        self._subscription_agreed = None
        self.discriminator = None

        self.subscription = subscription
        self.subscription_agreed = subscription_agreed

    @property
    def subscription(self):
        """Gets the subscription of this OrganizationUpdate.  # noqa: E501


        :return: The subscription of this OrganizationUpdate.  # noqa: E501
        :rtype: str
        """
        return self._subscription

    @subscription.setter
    def subscription(self, subscription):
        """Sets the subscription of this OrganizationUpdate.


        :param subscription: The subscription of this OrganizationUpdate.  # noqa: E501
        :type: str
        """
        if self.local_vars_configuration.client_side_validation and subscription is None:  # noqa: E501
            raise ValueError("Invalid value for `subscription`, must not be `None`")  # noqa: E501
        if (self.local_vars_configuration.client_side_validation and
                subscription is not None and len(subscription) < 1):
            raise ValueError("Invalid value for `subscription`, length must be greater than or equal to `1`")  # noqa: E501

        self._subscription = subscription

    @property
    def subscription_agreed(self):
        """Gets the subscription_agreed of this OrganizationUpdate.  # noqa: E501


        :return: The subscription_agreed of this OrganizationUpdate.  # noqa: E501
        :rtype: bool
        """
        return self._subscription_agreed

    @subscription_agreed.setter
    def subscription_agreed(self, subscription_agreed):
        """Sets the subscription_agreed of this OrganizationUpdate.


        :param subscription_agreed: The subscription_agreed of this OrganizationUpdate.  # noqa: E501
        :type: bool
        """
        if self.local_vars_configuration.client_side_validation and subscription_agreed is None:  # noqa: E501
            raise ValueError("Invalid value for `subscription_agreed`, must not be `None`")  # noqa: E501

        self._subscription_agreed = subscription_agreed

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, OrganizationUpdate):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, OrganizationUpdate):
            return True

        return self.to_dict() != other.to_dict()
